### ISSUE TITLE
RDP Session is not initiated in Windows 11 with SCALUS 1.1.0.317 version

### ISSUE THREAD

**Issue by CJaraGlez** [OneIdentity/SCALUS#156]
RDP Session is not initiated in Windows 11 with SCALUS 1.1.0.317 version

Could you help me?

[traza_scalus_not_launch_RDP.log](https://github.com/user-attachments/files/19270076/traza_scalus_not_launch_RDP.log)

**Comment by altiris4ever** [comment]
Should be fixed in the lastes 1.1.0.320 release:
Addressed issues https://github.com/OneIdentity/SCALUS/issues/146 https://github.com/OneIdentity/SCALUS/issues/153 - SCALUS session launcher did not work with the latest versions of web browsers such as Microsoft Edge, Firefox and Google Chrome https://github.com/OneIdentity/SCALUS/pull/148

**Comment by Basti890** [comment]
I still have the same issue on 1.1.0.320 our Safeguard for Privileged Password is ruuning on 7.0.5.

In the log is nothing too see not even any reaction ist seems like windows doesn't react at all to the URI RDP:-Protokol.

**Comment by MattBeaudinQC** [comment]
Hi @Basti890,

Do you still hit this issue on SPP 8.2 and 1.1.0.471? 

Matt

**Comment by CJaraGlez** [comment]
Hi @Basti890 , 

SCALUS now works with the new version of SSP. 

Thank you so much for your help and feedback.
